# Esto esta diciendo que necesitamos permisos de sudo para ejecutar esta build
sudo: required
# Necesitamos docker listo para empezar
services:
  - docker

before_install:
  - docker build -t abarranco/docker-react -f Dockerfile.dev .

  # Comandos a ejecutar para correr nuestros tests o lo que queramos. Se va a observar el status que se devuelve, si es distinto de 0 va a fallar.
  # Este programa npm run test nunca acaba, se quedará pillado porque espera input. Para evitar eso se añade -- --coverage
  script:
    - docker run abarranco/docker-react npm run test -- --coverage